# Generated by Django 3.0.3 on 2020-08-06 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_warrior'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warriors', to=settings.AUTH_USER_MODEL),
        ),
    ]
