# Generated by Django 3.0.3 on 2020-08-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_auto_20200810_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='year_in_school',
            new_name='action',
        ),
    ]
