# Generated by Django 3.0.3 on 2020-08-14 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_auto_20200812_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrior',
            name='strength',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
